// src/ui/fileList/solid2/FileListIsland.tsx
import { createEffect, createMemo, For, Show } from 'solid-js';
import { pathBasename } from '../../../lib/path/basename';
import {
	fileListNavigationCommandFromKey,
	resolveFileListNavigationTarget,
} from '../keyboardNavigation';
import {
	clearFiles,
	clearSelection,
	removeFile,
	restoreImportOrder,
	selectAll,
	selectFile,
	toggleSort,
} from './session';
import { displayedTitleForFile, readFileListView } from './view';
import {
	clearFileListCoverThumbnails,
	getFileListCoverThumbnailState,
	scheduleFileListCoverThumbnails,
} from './thumbnails';
import './FileListIsland.css';

export type FileListIslandProps = {
	isDragOver?: boolean;
	supportText?: string;
	onHeaderClick?: () => void;
	onHeaderKeydown?: (event: KeyboardEvent) => void;
};

export function FileListIsland(props: FileListIslandProps) {
	const view = createMemo(() => readFileListView());
	createEffect(
		() =>
			view()
				.files.filter((file) => file.isValid)
				.map((file) => file.path),
		(paths) => {
			if (paths.length === 0) clearFileListCoverThumbnails();
			else scheduleFileListCoverThumbnails(paths);
		},
	);

	function onKeyDown(event: KeyboardEvent) {
		const current = view();
		if (!current.files.length) return;
		const command = fileListNavigationCommandFromKey(event);
		if (command) {
			const targetIndex = resolveFileListNavigationTarget({
				command,
				fileCount: current.files.length,
				selectedIndex: current.selectedIndices[current.selectedIndices.length - 1] ?? -1,
			});
			if (targetIndex === null) return;
			event.preventDefault();
			selectFile(targetIndex);
			return;
		}
		const key = event.key.toLowerCase();
		if ((event.metaKey || event.ctrlKey) && key === 'a') {
			event.preventDefault();
			selectAll();
		} else if (key === 'escape') {
			event.preventDefault();
			clearSelection();
		}
	}

	return (
		<>
			<div class="file-list-toolbar">
				<span id="file-count-display">
					{view().files.length} {view().files.length === 1 ? 'file' : 'files'}
				</span>
				<span
					id="file-order-lock"
					data-testid="file-order-lock"
					style={{ display: view().orderLockVisible ? 'inline' : 'none' }}
				>
					Order locked while processing
				</span>
				<button
					type="button"
					id="sort-toggle-btn"
					style={{ display: view().showSortButton ? 'block' : 'none' }}
					disabled={view().sortDisabled}
					aria-label={`Sort files ${view().sortState === 'ascending' ? 'descending' : 'ascending'}`}
					onClick={() => toggleSort()}
				>
					{view().sortLabel}
				</button>
				<button
					type="button"
					id="restore-import-order-btn"
					style={{ display: view().orderDiffersFromImport ? 'block' : 'none' }}
					disabled={view().sortDisabled}
					onClick={() => restoreImportOrder()}
				>
					Restore import order
				</button>
				<button
					type="button"
					id="clear-files-btn"
					style={{ display: view().showClearButton ? 'block' : 'none' }}
					disabled={view().clearDisabled}
					onClick={() => clearFiles()}
				>
					Clear
				</button>
			</div>
			<section class="file-management-container" aria-label="File list">
				{/* biome-ignore lint/a11y: drop zone is a clickable region; Solid 2 JSX uses tabindex */}
				<div
					class={`drop-zone-header${props.isDragOver ? ' drag-over' : ''}`}
					data-has-files={String(view().files.length > 0)}
					role="button"
					aria-label="Add audio files"
					tabindex={0}
					onClick={() => props.onHeaderClick?.()}
					onKeyDown={(event) => props.onHeaderKeydown?.(event)}
				>
					<p>Drop files or folders here, click to choose files, or use Add Folder</p>
					<p>{props.supportText ?? ''}</p>
				</div>
				<div
					class="file-list-content"
					role="listbox"
					aria-label="Audio files"
					aria-multiselectable="true"
					tabindex={0}
					onKeyDown={onKeyDown}
				>
					<For each={view().files} keyed={(file) => file.inputId ?? file.path}>
						{(file, index) => {
							const selected = () => view().selectedIndices.includes(index());
							const readyUrl = () => {
								const state = getFileListCoverThumbnailState(file().path);
								return state.status === 'ready' ? state.dataUrl : undefined;
							};
							return (
								// biome-ignore lint/a11y: listbox option uses Solid 2 tabindex; keyboard stays on the listbox
								<div
									data-file-index={index()}
									class={`file-list-item${selected() ? ' selected' : ''}`}
									role="option"
									aria-selected={selected() ? 'true' : 'false'}
									aria-label={pathBasename(file().path, { fallback: 'path' })}
									tabindex={-1}
									onClick={(event) =>
										selectFile(index(), {
											multi: event.ctrlKey || event.metaKey,
											range: event.shiftKey,
										})
									}
								>
									<div class="file-cover-thumbnail" aria-hidden="true">
										<Show when={readyUrl()} fallback={<span>Art</span>}>
											{(url) => <img src={url()} alt="" />}
										</Show>
									</div>
									<span>{file().isValid ? '✓' : '✗'}</span>
									<span>{displayedTitleForFile(file())}</span>
									<button
										type="button"
										class="remove-file-btn"
										disabled={view().orderLockVisible}
										onClick={(event) => {
											event.stopPropagation();
											removeFile(index());
										}}
									>
										×
									</button>
								</div>
							);
						}}
					</For>
				</div>
			</section>
			<aside data-testid="file-list-inspector" aria-label="Selected file inspector">
				<p data-testid="inspector-context">{view().inspector.contextText}</p>
				<p data-testid="inspector-detail">{view().inspector.contextDetail}</p>
				<p data-testid="inspector-size">{view().inspector.fileSizeText}</p>
				<p data-testid="inspector-combined">{view().combinedSizeText}</p>
			</aside>
		</>
	);
}

// src/ui/fileList/FileListIsland.svelte
<script lang="ts">
	import { pathBasename } from '../../lib/path/basename';
	import { formatDuration, formatFileSize } from '../../types/audio';
	import { clearAllFiles, restoreImportOrder, toggleFileSort } from './actions';
	import {
		createFileListPointerReorder,
		onFileListClick,
		onFileListKeyDown,
		onFileListMoveDown,
		onFileListMoveUp,
		onFileListRemove,
	} from './events';
	import { getCurrentFileList } from './state.svelte';
	import {
		clearFileListCoverThumbnails,
		getFileListCoverThumbnailState,
		scheduleFileListCoverThumbnails,
	} from './coverThumbnails.svelte';
	import {
		readFileListControlsSnapshot,
		displayedArtistForFile,
		displayedTitleForFile,
		readFileListOrderLockVisible,
		readFileListSelectedIndices,
		readFileListOrderDiffersFromImport,
		readFileListSortLabel,
		readFileListSortState,
		readFileListViewFiles,
	} from './viewState.svelte';
	import { hasSupplementalAssetsForInputId } from '../remoteSource';

	interface Props {
		isDragOver?: boolean;
		supportText?: string;
		onHeaderClick?: () => void;
		onHeaderKeydown?: (event: KeyboardEvent) => void;
		fileManagementContainer?: HTMLDivElement | null;
	}

	let {
		isDragOver = false,
		supportText = '',
		onHeaderClick,
		onHeaderKeydown,
		fileManagementContainer = $bindable(null),
	}: Props = $props();

	let fileListContent: HTMLDivElement | null = null;
	let draggedIndex = $state<number | null>(null);
	let hoveredIndex = $state<number | null>(null);
	let hoveredEdge = $state<'top' | 'bottom' | null>(null);

	const files = $derived(readFileListViewFiles());
	const selectedIndices = $derived(readFileListSelectedIndices());
	const sortLabel = $derived(readFileListSortLabel());
	const sortState = $derived(readFileListSortState());
	const orderDiffersFromImport = $derived(readFileListOrderDiffersFromImport());
	const controls = $derived(readFileListControlsSnapshot());
	const orderLockVisible = $derived(readFileListOrderLockVisible());
	const hasFiles = $derived((getCurrentFileList()?.files.length ?? 0) > 0);

	const reorderHandlers = createFileListPointerReorder((state) => {
		draggedIndex = state.draggedIndex;
		hoveredIndex = state.hoveredIndex;
		hoveredEdge = state.hoveredEdge;
	});

	function focusFileListContent(): void {
		fileListContent?.focus({ preventScroll: true });
	}

	function handleFileListClick(index: number, event: MouseEvent): void {
		if (reorderHandlers.consumePostDragClick()) return;
		focusFileListContent();
		onFileListClick(index, event);
	}

	function handleSortClick(): void {
		void toggleFileSort();
	}

	function handleRestoreImportOrder(): void {
		void restoreImportOrder();
	}

	function handleClearClick(): void {
		clearAllFiles();
	}

	function getFileName(path: string): string {
		return pathBasename(path, { fallback: 'path' });
	}

	function formatFileDetails(file: (typeof files)[number]): string {
		const artist = displayedArtistForFile(file);
		const artistPrefix = artist ? `${artist} • ` : '';
		const chapterSuffix = file.chapters?.length
			? ` • ${file.chapters.length} chapter${file.chapters.length === 1 ? '' : 's'}`
			: '';
		if (file.isValid && file.duration && file.size) {
			return `${artistPrefix}${formatDuration(file.duration)} • ${formatFileSize(file.size)} • ${file.format}${chapterSuffix}`;
		}
		return `Error: ${file.error || 'Invalid file'}`;
	}

	function scrollSelectedFileIntoView(index: number): void {
		requestAnimationFrame(() => {
			const selectedItem = fileListContent?.querySelector<HTMLElement>(
				`[data-file-index="${index}"]`,
			);
			selectedItem?.scrollIntoView({ block: 'nearest' });
		});
	}

	$effect(() => {
		const validPaths = files.filter((file) => file.isValid).map((file) => file.path);
		let active = true;
		queueMicrotask(() => {
			if (!active) return;
			if (validPaths.length === 0) {
				clearFileListCoverThumbnails();
				return;
			}
			scheduleFileListCoverThumbnails(validPaths);
		});
		return () => {
			active = false;
		};
	});

	$effect(() => {
		const selectedIndex = selectedIndices[selectedIndices.length - 1];
		if (typeof selectedIndex !== 'number') return;

		scrollSelectedFileIntoView(selectedIndex);
	});
</script>

<div class="flex flex-col gap-2 mb-2">
	<div class="flex items-center justify-end gap-2">
		<div class="flex items-center gap-2 mr-auto self-center pl-1">
			<span class="text-xs muted-text italic" id="file-count-display">
				{files.length}
				{files.length === 1 ? 'file' : 'files'}
			</span>
			<span
				class="text-xs muted-text italic"
				id="file-order-lock"
				style:display={orderLockVisible ? 'inline' : 'none'}
				data-testid="file-order-lock"
			>
				Order locked while processing
			</span>
		</div>
		<button
			id="sort-toggle-btn"
			class="btn-pill btn-pill-secondary"
			style:display={controls.showSortButton ? 'block' : 'none'}
			disabled={controls.sortDisabled}
			aria-label={`Sort files ${sortState === 'ascending' ? 'descending' : 'ascending'}`}
			aria-describedby="file-sort-status"
			onclick={handleSortClick}
		>
			{sortLabel}
		</button>
		<span id="file-sort-status" class="sr-only" aria-live="polite">
			{sortState === 'ascending'
				? 'Files sorted from A to Z.'
				: sortState === 'descending'
					? 'Files sorted from Z to A.'
					: 'Files are in import order.'}
		</span>
		<button
			id="restore-import-order-btn"
			class="btn-pill btn-pill-secondary"
			style:display={orderDiffersFromImport ? 'block' : 'none'}
			disabled={controls.sortDisabled}
			onclick={handleRestoreImportOrder}
		>
			Restore import order
		</button>
		<button
			id="clear-files-btn"
			class="btn-pill btn-pill-secondary"
			style:display={controls.showClearButton ? 'block' : 'none'}
			disabled={controls.clearDisabled}
			onclick={handleClearClick}
		>
			Clear
		</button>
	</div>
</div>

<style>
	.file-management-container {
		display: flex;
		flex: 1 1 auto;
		flex-direction: column;
		min-height: 8rem;
		overflow: hidden;
		border: 1px solid var(--border-primary);
		border-radius: 0.375rem;
		background-color: var(--bg-input);
	}

	.file-list-content:focus-visible {
		outline: 2px solid var(--border-focus);
		outline-offset: -2px;
	}

	.drop-zone-header[data-has-files='false'] {
		display: flex;
		flex: 1 1 auto;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		padding: 2rem 1rem;
		border: 2px dashed var(--border-secondary);
		background-color: var(--bg-drag-area);
		cursor: pointer;
		transition: all 0.2s ease;
	}

	.drop-zone-header[data-has-files='false']:hover,
	.drop-zone-header[data-has-files='false'].drag-over {
		border-color: var(--accent-primary);
		background-color: var(--bg-hover);
	}

	.drop-zone-header[data-has-files='false'].drag-over {
		transform: scale(1.02);
	}

	.drop-zone-header[data-has-files='false']:focus {
		outline: 2px solid var(--border-focus);
		outline-offset: 2px;
	}

	.drop-zone-header[data-has-files='true'] {
		flex-shrink: 0;
		min-height: 2.5rem;
		padding: 0.5rem 1rem;
		border-bottom: 1px solid var(--border-primary);
		background-color: var(--bg-input);
		cursor: pointer;
		transition: all 0.2s ease;
	}

	.drop-zone-header[data-has-files='true']:hover {
		background-color: var(--bg-hover);
	}

	.drop-zone-header[data-has-files='true']:focus {
		outline: 2px solid var(--border-focus);
		outline-offset: -2px;
	}

	.file-list-content {
		flex: 1 1 auto;
		min-height: 0;
		overflow-y: auto;
	}

	.file-list-item {
		padding: 0.75rem;
		border-bottom: 1px solid var(--border-primary);
		cursor: pointer;
		transition: background-color 0.2s ease;
		user-select: none;
	}

	.file-list-item:last-child {
		border-bottom: none;
	}

	.file-list-item:hover {
		background-color: var(--bg-hover);
	}

	.file-list-item.selected {
		background-color: var(--accent-primary);
		color: var(--text-inverse);
	}

	.file-list-item.dragging {
		opacity: 0.5;
	}

	.file-list-item.drag-over {
		border-top: 2px solid var(--accent-primary);
	}

	.file-item-content {
		display: flex;
		align-items: center;
		gap: 0.75rem;
		min-width: 0;
	}

	.file-status {
		min-width: 1rem;
		font-size: 1rem;
		font-weight: bold;
	}

	.file-cover-thumbnail {
		display: flex;
		align-items: center;
		justify-content: center;
		width: 2rem;
		height: 2rem;
		flex: 0 0 2rem;
		overflow: hidden;
		border-radius: 0.25rem;
		background: var(--bg-drag-area);
		color: var(--text-muted);
		font-size: 0.625rem;
	}

	.file-cover-thumbnail img {
		width: 100%;
		height: 100%;
		object-fit: cover;
	}

	.file-info {
		flex: 1;
		min-width: 0;
	}

	.file-name-row {
		display: flex;
		align-items: center;
		gap: 0.375rem;
		margin-bottom: 0.25rem;
		min-width: 0;
	}

	.file-name {
		min-width: 0;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
		font-size: 0.875rem;
		font-weight: 500;
	}

	.companion-chip {
		flex: 0 0 auto;
		padding: 0.0625rem 0.25rem;
		border: 1px solid var(--accent-primary);
		border-radius: 0.25rem;
		background-color: rgb(59 130 246 / 0.12);
		color: var(--accent-primary);
		font-size: 0.625rem;
		font-weight: 600;
		line-height: 1;
	}

	.file-list-item.selected .companion-chip {
		border-color: rgb(255 255 255 / 0.7);
		background-color: rgb(255 255 255 / 0.18);
		color: var(--text-inverse);
	}

	.file-details {
		overflow: hidden;
		color: var(--text-muted);
		text-overflow: ellipsis;
		white-space: nowrap;
		font-size: 0.75rem;
	}

	.file-list-item.selected .file-details {
		color: var(--text-inverse);
		opacity: 0.9;
	}

	.remove-file-btn,
	.move-up-btn,
	.move-down-btn {
		display: flex;
		align-items: center;
		justify-content: center;
		width: 1.5rem;
		height: 1.5rem;
		padding: 0.25rem;
		border: none;
		border-radius: 0.25rem;
		background: none;
		color: var(--text-muted);
		font-size: 1.25rem;
		font-weight: bold;
		cursor: pointer;
	}

	.remove-file-btn:hover {
		background-color: rgb(239 68 68 / 0.1);
		color: #ef4444;
	}

	.move-up-btn:hover,
	.move-down-btn:hover {
		background-color: var(--bg-hover);
		color: var(--accent-primary);
		transform: translateY(-1px);
	}

	.move-up-btn:focus-visible,
	.move-down-btn:focus-visible {
		outline: 2px solid var(--border-focus);
		outline-offset: 2px;
	}

	.move-up-btn:disabled,
	.move-down-btn:disabled {
		opacity: 0.3;
		cursor: not-allowed;
	}

	.move-up-btn:disabled:hover,
	.move-down-btn:disabled:hover {
		background-color: transparent;
		color: var(--text-muted);
		transform: none;
	}

	.file-list-item.selected .remove-file-btn,
	.file-list-item.selected .move-up-btn,
	.file-list-item.selected .move-down-btn {
		color: var(--text-inverse);
		opacity: 0.8;
	}

	.file-list-item.selected .remove-file-btn:hover,
	.file-list-item.selected .move-up-btn:hover,
	.file-list-item.selected .move-down-btn:hover {
		background-color: rgb(255 255 255 / 0.2);
		color: var(--text-inverse);
		opacity: 1;
	}

	.file-list-item.selected .move-up-btn:disabled,
	.file-list-item.selected .move-down-btn:disabled {
		color: var(--text-inverse);
	}
</style>

<div
	class="file-management-container mb-3"
	role="region"
	aria-label="File list"
	bind:this={fileManagementContainer}
>
	<div
		class="drop-zone-header"
		class:drag-over={isDragOver}
		data-has-files={hasFiles.toString()}
		role="button"
		aria-label="Add audio files"
		tabindex="0"
		onclick={() => onHeaderClick?.()}
		onkeydown={(event) => onHeaderKeydown?.(event)}
	>
		<p class="text-sm muted-text">
			Drop files or folders here, click to choose files, or use Add Folder
		</p>
		<p class="text-xs muted-text mt-1">{supportText}</p>
	</div>

	<!-- svelte-ignore a11y_click_events_have_key_events a11y_no_noninteractive_element_interactions -->
	<div
		bind:this={fileListContent}
		class="file-list-content"
		role="listbox"
		aria-label="Audio files"
		aria-multiselectable="true"
		tabindex="0"
		onkeydown={onFileListKeyDown}
	>
		{#each files as file, index (file.inputId ?? file.path)}
			{@const thumbnail = getFileListCoverThumbnailState(file.path)}
			<div
				data-file-index={index}
				class="file-list-item {file.isValid ? 'valid' : 'invalid'}"
				class:selected={selectedIndices.includes(index)}
				class:dragging={draggedIndex === index}
				class:drag-over={hoveredIndex === index}
				data-drop-edge={hoveredIndex === index ? hoveredEdge : undefined}
				role="option"
				aria-selected={selectedIndices.includes(index)}
				aria-label={getFileName(file.path)}
				tabindex="-1"
				onclick={(event) => handleFileListClick(index, event)}
			>
				<div class="file-item-content">
					<span
						class="file-reorder-grip"
						role="button"
						tabindex="-1"
						aria-label={`Reorder ${getFileName(file.path)}`}
						onpointerdown={(event) => reorderHandlers.onGripPointerDown(index, event)}
						onclick={(event) => event.stopPropagation()}
					>
						⋮⋮
					</span>
				<div class="file-cover-thumbnail" aria-hidden="true">
						{#if thumbnail.status === 'ready'}
							<img src={thumbnail.dataUrl} alt="" />
						{:else}
							<span>Art</span>
						{/if}
					</div>
					<div class="file-status {file.isValid ? 'text-green-500' : 'text-red-500'}">
						{file.isValid ? '✓' : '✗'}
					</div>
					<div class="file-info">
						<div class="file-name-row">
							<div class="file-name">{displayedTitleForFile(file)}</div>
							{#if hasSupplementalAssetsForInputId(file.inputId)}
								<span class="companion-chip" title="Supplemental PDF attached">PDF</span>
							{/if}
						</div>
						<div class="file-details">{formatFileDetails(file)}</div>
					</div>
					<button
						class="move-up-btn"
						onclick={(event) => {
							event.stopPropagation();
							onFileListMoveUp(index, event);
						}}
						disabled={index === 0 || orderLockVisible}
					>
						▲
					</button>
					<button
						class="move-down-btn"
						onclick={(event) => {
							event.stopPropagation();
							onFileListMoveDown(index, event);
						}}
						disabled={index === files.length - 1 || orderLockVisible}
					>
						▼
					</button>
					<button
						class="remove-file-btn"
						disabled={orderLockVisible}
						onclick={(event) => {
							event.stopPropagation();
							onFileListRemove(index, event);
						}}
					>
						×
					</button>
				</div>
			</div>
		{/each}
	</div>
</div>
